### ISSUE TITLE
Secrets Provider - JSON schema vs functions

### ISSUE THREAD

**Issue by sigalsax** [cyberark/secrets-provider-for-k8s#164] opened 2020-07-29 07:13 UTC
DOD

- [x] Check if we will use JSON schema or HELM functions
- [ ] Talk to @oburstein-hub about what is mainstream and recommendations
- [ ] Create a schema/functions for the helm charts

**Comment by abrahamko** [comment] 2020-08-03 10:43
Duplicate of #169

**Closed** 2020-08-03 10:43 UTC
